### ISSUE TITLE
Using !clear and !nowplaying creates exception

### ISSUE THREAD

**Issue by mrdarj** [squigjess/JukeBot#22]
Exception for array out of bounds on server when using !clear followed by !nowplaying

Currently playing song will still finish

**Comment by squigjess** [comment]
Could you please let me know if you're using the `live` branch or the `testing`  branch? If you're using the `testing` branch, could you please let me know if the issue persists after updating to the most recent `testing` version?

**Comment by mrdarj** [comment]
> Could you please let me know if you're using the `live` branch or the `testing` branch? If you're using the `testing` branch, could you please let me know if the issue persists after updating to the most recent `testing` version?

This was on live. Issue is not there on testing

**Comment by squigjess** [comment]
Thanks for clarifying! I'll take a look later on today and update you when the change is pushed to `live`.

**Comment by squigjess** [comment]
Issue was fixed in the `testing` branch, which has just been pushed to `live` now.
