### ISSUE TITLE
[Windows] Log File Error OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by mrdarj** [squigjess/JukeBot#23]
OS: Windows
Branch: live and testing
Workaround: Changing config.py 
from:

LOG_FILE_NAME = f"jukebot_{exec_time}.log"

to:
LOG_FILE_NAME = f"jukebot.log"

```
ERROR:root:=====================================================================================
ERROR:root:UNHANDLED GENERIC ERROR, PLEASE REPORT TO https://github.com/squigjess/JukeBot/issues
Traceback (most recent call last):
  File "C:\JukeBot-testing\src\bot.py", line 87, in <module>
    initialise()
  File "C:\JukeBot-testing\src\bot.py", line 35, in initialise
    logging.basicConfig(filename=JukeBot.config.LOG_FILE_PATH,
  File "C:\Users\removed\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 2031, in basicConfig
    h = FileHandler(filename, mode,
  File "C:\Users\removed\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1167, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\removed\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1197, in _open
    return open_func(self.baseFilename, self.mode,
OSError: [Errno 22] Invalid argument: 'C:\\JukeBot-testing\\src\\logs\\jukebot_02-11-2021_13:00:59.log'
ERROR:root:=====================================================================================
```

**Comment by mrdarj** [comment]
Error does not occur on linux-Ubuntu- testing branch

**Comment by mrdarj** [comment]
Editted previous comment out because it was useless

Changing line exec_time = datetime.now().strftime("%d-%m-%Y_%H:%M:%S") fixes it

From %H:%M:%S

To %H-%M-%S

Perhaps windows doesn't like the : in filename?

Windows 11 btw

@squigjess

**Comment by squigjess** [comment]
Yeah, that makes a lot of sense, re: Windows not liking colons in file names.
Thanks for the additional testing!!

**Comment by squigjess** [comment]
Bug hopefully fixed. Could you please advise whether or not the issue persists on Windows with the latest `live` version?

**Comment by mrdarj** [comment]
Howdy,

Copied just the updated config.py into my live folder and can confirm it did not throw error

Cheers

**Comment by squigjess** [comment]
Thanks so much for helping with this! I greatly appreciate it.
